# Generated by Django 4.1.4 on 2022-12-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
