# Generated by Django 4.1.4 on 2022-12-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_consult_delete_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='para',
            new_name='to',
        ),
    ]
